# Device Profile Template

Source this file in scripts or workflow docs to reference device settings.
Each device gets its own copy: `configs/device-<name>.sh`

## Fields

| Field | Required | Values | Description |
|:------|:---------|:-------|:------------|
| `DEVICE_NAME` | ✅ | string | Human-readable name |
| `DEVICE_ROLE` | ✅ | `dev` / `train` / `dev+train` / `check` | What the device is used for |
| `SSH_HOST` | ✅ | IP or hostname | SSH target |
| `SSH_PORT` | ✅ | number | SSH port |
| `SSH_USER` | ✅ | string | SSH login user |
| `SSH_AUTH` | ✅ | `password` / `key` / `askpass` | Authentication method |
| `SSH_MODE` | ✅ | `direct` / `reverse` / `overlay` | Connection pattern |
| `OVERLAY_TYPE` | ❌ | `netbird` / `zerotier` / `easytier` | Overlay network type |
| `OVERLAY_IP` | ❌ | IP | Overlay IP address |
| `GODOT_PATH` | ✅ | path | Full path to Godot binary |
| `GODOT_DOTNET` | ✅ | `true` / `false` | Is this the .NET edition? |
| `MCP_ENABLED` | ✅ | `true` / `false` | Is godot-mcp installed? |
| `MCP_PORT` | ❌ | number | MCP server HTTP port |
| `HAS_GPU` | ✅ | `true` / `false` |
| `TRAINING_FRAMEWORKS` | ❌ | `sb3` / `cleanrl` / `sample_factory` | Installed RL frameworks |
| `PYTHON_ENV` | ❌ | `uv` / `conda` / `venv` | Python environment manager |

## Template

```bash
# configs/device-<name>.sh
# Auto-generated by Hermes. Edit as needed.

DEVICE_NAME="<Human name>"
DEVICE_ROLE="dev+train"       # dev / train / dev+train / check

# --- SSH ---
SSH_MODE="direct"             # direct / reverse / overlay
SSH_HOST="<ip_or_hostname>"
SSH_PORT=22
SSH_USER="<username>"
SSH_AUTH="key"                # password / key / askpass

# --- Overlay (optional) ---
OVERLAY_TYPE=""
OVERLAY_IP=""

# --- Godot ---
GODOT_PATH="/path/to/godot"
GODOT_DOTNET=true

# --- MCP (optional) ---
MCP_ENABLED=false
MCP_PORT=14095

# --- Training ---
HAS_GPU=false
TRAINING_FRAMEWORKS=""
PYTHON_ENV="uv"
```
